version: "3.9"
services:
  api:
    build: ./server
    depends_on:
      - redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      SUBGRAPH_API_KEY: ${SUBGRAPH_API_KEY}
      SUBGRAPH_UPDATE_SLEEP_SEC: ${SUBGRAPH_UPDATE_SLEEP_SEC}
    ports:
      - "${API_PORT}:${API_PORT}"
    command:
      [
        "uvicorn", "app.main:app",
        "--host", "${API_HOST}",
        "--port", "${API_PORT}",
        "--workers", "${NUM_WORKERS}"
      ]
  redis:
    image: "redis:alpine"
    ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --port ${REDIS_PORT}
